### PR TITLE
handle shift to python 3.12

### LINKED ISSUE #176: MutateX is incompatible with BioPython >1.78
see #175 - the cause is the fact that `PDB.Polypeptide.three_to_one` has been replaced in newer versions. We will consider it when upgrading and retesting MutateX for more recent Python versions

### LINKED ISSUE #183: Plotting modules are getting deprecated
Depreciation warnings: 

MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead

Is applicable for: 
* ddg2distribution
* ddg2heatmap

For ddg2density 

Please import `gaussian_kde` from the `scipy.stats` namespace; the `scipy.stats.kde` namespace is deprecated and will be removed in SciPy 2.0.0.
`from scipy.stats.kde import gaussian_kde`

### PR DESCRIPTION
**Pull request by DegnKristine**
fix #183 and #176 to update to newest biopython. 

This should also fix the challenge described in #170

### CODE REVIEW

**Comment by DegnKristine** [comment]
Now running basic_multimers... FAILED

WARNING:root:Input amino acid sequence and input position sequence is not identical in multimer.
ERROR:root:The supplied PDB files must have identical positions of sequences. Exiting...

Potential issues with the new "three to one" implementation disallowing 'AGLU' 'BGLU' for example

**Comment by mtiberti** [comment]
thank you, answering your points:

  - I don't think that is the expected behaviour: MutateX should identify that there is one multimer of 2 chains (B and D) and two single chains (A and C). This test is designed on purpose to be complicated and not have just one multimer of four chains. Only chains *of different PDB files* are supposed to have the same sequence. In fact, the error is `The supplied PDB files must have identical positions of sequences`; this is wrong because we only have one PDB file, so this check shouldn't be failing
  - do you think you can find the cause of the second crash? It's possible it's not due to the Biopython problem

**Comment by DegnKristine** [comment]
#176

**Comment by DegnKristine** [comment]
29/Feb/2024 - Failed tests

`Now running basic_multimers... FAILED`, `mutatex.log`
```
WARNING:root:Input amino acid sequence and input position sequence is not identical in multimer.
ERROR:root:The supplied PDB files must have identical positions of sequences. Exiting...
```
Error raised in line 456 of utils.py. 

`Now running interaction... FAILED` - all interaction tests fail all related to "str" handling  -`mutatex.log`
Crash in relation to string handling, a known python 3.12 update. Called via:
`original_residues_dictionary[key] = get_foldx_sequence(pdb, multimers=args.multimers)`

`TypeError: can only concatenate str (not "NoneType") to str`

**Comment by DegnKristine** [comment]
Interactions. 

`Now running interaction... FAILED` - all interaction tests fail all related to "str" handling  -`mutatex.log`
Crash in relation to string handling, a known python 3.12 update. Called via:
`original_residues_dictionary[key] = get_foldx_sequence(pdb, multimers=args.multimers)`

`TypeError: can only concatenate str (not "NoneType") to str`

**Pull request closed without merging**
